feat: implement check query plan workflow with dynamic artifact retrieval

diff --git a/.github/workflows/check-query-plan.yaml b/.github/workflows/check-query-plan.yaml
--- a/.github/workflows/check-query-plan.yaml
+++ b/.github/workflows/check-query-plan.yaml
@@ -1,42 +1,62 @@
-#name: Check Query Plan
-#on:
-#  pull_request:
-#    paths:
-#      # This workflow should run every time router-ci and cli-ci runs
-#      - 'cli/**/*'
-#      - 'connect/**/*'
-#      - '.github/workflows/cli-ci.yaml'
-#      - 'composition-go/**/*'
-#      - 'demo/**/*'
-#      - 'router/**/*'
-#      - 'router-tests/**/*'
-#      - 'connect/**/*'
-#      - '.github/workflows/router-ci.yaml'
-#  workflow_run:
-#    workflows: [ "wgc CI", "Router CI" ]
-#    types: [ completed ]
-#
-#jobs:
-#  check_query_plan:
-#    runs-on: ubuntu-latest
-#    steps:
-#      - name: Wait Router CI
-#        uses: NathanFirmo/wait-for-other-action@v1.0.4
-#        continue-on-error: true
-#        with:
-#          token: ${{ secrets.GITHUB_TOKEN }}
-#          workflow: 'router-ci.yml'
-#      - name: Wait Cli CI
-#        uses: NathanFirmo/wait-for-other-action@v1.0.4
-#        continue-on-error: true
-#        with:
-#          token: ${{ secrets.GITHUB_TOKEN }}
-#          workflow: 'cli-ci.yml'
-#      - name: Get Cli bun artifact URL
-#        uses: actions/download-artifact@v2
-#        with:
-#          name: wgc-experimental-${{ github.sha }}-linux-amd64
-#      - name: Get Router image or use the default
-#        run:
-#          jobId=`gh run list -e pull_request -w "router-ci.yaml" -b ale/eng-6601-regression-tester -c ${{ github.sha }} --json databaseId,createdAt --status completed | jq "sort_by(.createdAt) | .[0].databaseId"`
-#          echo "router=ghcr.io/wundergraph/cosmo/router:sha-${{ github.sha }}" >> $GITHUB_OUTPUT
+name: Check Query Plan
+on:
+  pull_request:
+    paths:
+      # This workflow should run every time router-ci and cli-ci runs
+      - 'cli/**/*'
+      - 'connect/**/*'
+      - '.github/workflows/cli-ci.yaml'
+      - 'composition-go/**/*'
+      - 'demo/**/*'
+      - 'router/**/*'
+      - 'router-tests/**/*'
+      - 'connect/**/*'
+      - '.github/workflows/router-ci.yaml'
+
+jobs:
+  check_query_plan:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Wait Router CI and get image URL
+        id: wait-router-ci
+        run: |
+          runId=`gh run list -e pull_request -w "router-ci.yaml" -c ${{ github.sha }} --json databaseId,createdAt | jq "sort_by(.createdAt) | reverse | .[0].databaseId"`
+          router="ghcr.io/wundergraph/cosmo/router:latest"
+          if [ ! -z "$runId" ]; then
+            gh run watch $runId
+            router="ghcr.io/wundergraph/cosmo/router:sha-${{ github.sha }}"
+          fi
+          echo "router=$router" >> $GITHUB_OUTPUT
+      - name: Wait CLI CI and get wgc artifact URL or name
+        id: wait-cli-ci
+        run: |
+          runId=`gh run list -e pull_request -w "cli-ci.yaml" -c ${{ github.sha }} --json databaseId,createdAt | jq "sort_by(.createdAt) | .[0].databaseId"`
+          wgc="latest"
+          if [ ! -z "$runId" ]; then
+            gh run watch $runId
+            artifact_url=`gh api \
+              -H "Accept: application/vnd.github+json" \
+              -H "X-GitHub-Api-Version: 2022-11-28" \
+              /repos/wundergraph/cosmo/actions/runs/$runId/artifacts -q '.artifacts[] | select(.name == "wgc-experimental-${{ github.sha }}-bun-linux-x64") | .["archive_download_url"]'`
+            if [ -z "$artifact_url" ]; then
+              echo "Failed to get artifact URL"
+              exit 1
+            fi
+            wgc=$artifact_url
+          fi
+          echo "wgc=$wgc" >> $GITHUB_OUTPUT
+      - uses: convictional/trigger-workflow-and-wait@v1.6.5
+        name: Trigger Query Planner CI
+        with:
+          owner: wundergraph
+          repo: cosmo-celestial
+          ref: master
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          propagate_failure: true
+          workflow_file_name: 'query-planner-tester.yaml'
+          client_payload: >-
+            {
+              "router": "${{ steps.wait-router-ci.outputs.router }}",
+              "wgc": "${{ steps.wait-cli-ci.outputs.wgc }}",
+              "token": "${{secrets.GITHUB_TOKEN}}"
+            }
